type: test_results_container
schema: tcms/testcase_results_container.schema.v1.json
title: Full Featured Test Report
project: Full Featured Test Project
environment: Production
platform: macOS ARM64
executor: Jenkins v3.2.1
