#!/usr/bin/env bash
# Setup git hooks for projector integration
# This script creates pre-commit and pre-push hooks that run projector workflows

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/logger.sh" || exit 1

GIT_HOOKS_DIR=".git/hooks"

# Check if we're in a git repository
if [ ! -d ".git" ]; then
    log_error "Not in a git repository. Please run this script from the repository root."
    exit 1
fi

# Check if projector is installed
if ! command -v projector >/dev/null 2>&1; then
    log_warning "Projector is not installed or not in PATH."
    log_info "Install it from: https://github.com/alvarogarcia7/projector"
    log_info "This script will create hooks that assume projector will be available."
fi

# Create hooks directory if it doesn't exist
mkdir -p "$GIT_HOOKS_DIR"

section "Setting up Projector Git Hooks"

# Create pre-commit hook
log_info "Creating pre-commit hook..."
cat > "$GIT_HOOKS_DIR/pre-commit" << 'EOF'
#!/usr/bin/env bash
# Pre-commit hook - runs projector pre-commit workflow
# Generated by scripts/setup-projector-hooks.sh

set -e

echo "Running pre-commit checks with projector..."

# Check if projector is available
if ! command -v projector >/dev/null 2>&1; then
    echo "Warning: projector not found. Running make commands directly..."
    make lint && make build && make test-unit && make verify-scripts
    exit $?
fi

# Run projector pre-commit workflow
projector run pre-commit

exit $?
EOF

chmod +x "$GIT_HOOKS_DIR/pre-commit"
pass "Pre-commit hook created"

# Create pre-push hook
log_info "Creating pre-push hook..."
cat > "$GIT_HOOKS_DIR/pre-push" << 'EOF'
#!/usr/bin/env bash
# Pre-push hook - runs projector pre-push workflow
# Generated by scripts/setup-projector-hooks.sh

set -e

echo "Running pre-push checks with projector..."

# Check if projector is available
if ! command -v projector >/dev/null 2>&1; then
    echo "Warning: projector not found. Running make commands directly..."
    make lint && make build && make test-unit && make test-e2e && make verify-scripts
    exit $?
fi

# Run projector pre-push workflow
projector run pre-push

exit $?
EOF

chmod +x "$GIT_HOOKS_DIR/pre-push"
pass "Pre-push hook created"

section "Git Hooks Setup Complete"

log_info "The following hooks have been created:"
log_info "  - pre-commit: Runs format, lint, build, unit tests, and script verification"
log_info "  - pre-push: Runs all pre-commit checks plus e2e tests"
log_info ""
log_info "To disable hooks temporarily, use:"
log_info "  git commit --no-verify"
log_info "  git push --no-verify"
log_info ""
log_info "To remove hooks, delete:"
log_info "  rm $GIT_HOOKS_DIR/pre-commit"
log_info "  rm $GIT_HOOKS_DIR/pre-push"
